export interface ChecklistSection {
  number: number;
  name: string;
  items: string[];
}

export const QC_CHECKLIST_SECTIONS: ChecklistSection[] = [
  {
    number: 1,
    name: "Modular Planning Verification",
    items: [
      "Modular grid defined and consistent across all drawings",
      "Module sizes coordinated with transport limitations",
      "Module numbering system finalized and unique",
      "Module boundaries clearly marked in plans",
      "Structural grid aligned with module grid",
      "Floor levels defined (FFL, SSL etc.)",
      "Floor-to-floor heights coordinated",
      "Ceiling heights verified",
      "Stacking modules vertically aligned",
      "Structural load transfer modules confirmed",
    ],
  },
  {
    number: 2,
    name: "Transport & Logistics",
    items: [
      "Module width within transport limits",
      "Module height within transport limits",
      "Module length within transport limits",
      "Maximum module weight verified",
      "Crane lifting capacity verified",
      "Lifting points clearly indicated",
      "Temporary bracing for transport provided",
      "Sensitive materials protected for transport",
      "Module center of gravity considered",
    ],
  },
  {
    number: 3,
    name: "Structural Coordination",
    items: [
      "Structural grid matches architectural grid",
      "Column and beam locations verified",
      "Beam depths coordinated with ceiling heights",
      "Clash check done with openings and MEP",
      "Bracing locations verified",
      "Base plate locations confirmed",
      "Anchor bolt positions coordinated",
      "Steel sections labeled clearly",
      "Weld specifications provided",
      "Bolt specifications provided",
    ],
  },
  {
    number: 4,
    name: "Floor System",
    items: [
      "Floor framing layout defined",
      "Decking sheet specification provided",
      "Floor build-up layers defined",
      "Thermal and acoustic insulation defined",
      "Wet area floor depressions provided",
      "Bathroom floor slopes indicated",
      "Floor trap locations coordinated",
      "Floor load capacity verified",
    ],
  },
  {
    number: 5,
    name: "External Wall Systems",
    items: [
      "Wall thickness defined",
      "Panel system specified",
      "Insulation specified",
      "Fire rating defined",
      "Cladding system defined",
      "Panel fixing details provided",
      "Joint waterproofing details provided",
    ],
  },
  {
    number: 6,
    name: "Windows & Glazing",
    items: [
      "Window schedule complete",
      "Window sizes coordinated with panels",
      "Sill heights verified",
      "Head heights verified",
      "Glass specification defined",
      "Waterproof flashing details provided",
    ],
  },
  {
    number: 7,
    name: "Doors",
    items: [
      "Door schedule complete",
      "Door sizes verified",
      "Door swings indicated",
      "Frame types specified",
      "Hardware schedule provided",
      "Threshold details provided",
    ],
  },
  {
    number: 8,
    name: "Bathrooms & Wet Areas",
    items: [
      "Waterproofing layers defined",
      "Floor slopes defined",
      "Drain locations defined",
      "Pipe sleeves coordinated",
      "Exhaust provision provided",
    ],
  },
  {
    number: 9,
    name: "Electrical",
    items: [
      "Electrical entry defined",
      "Panel board location defined",
      "Switches and sockets coordinated",
      "Lighting layout verified",
      "Data points defined",
    ],
  },
  {
    number: 10,
    name: "Plumbing",
    items: [
      "Water supply routing defined",
      "Drain pipe routing defined",
      "Vent pipes defined",
      "External connection points defined",
    ],
  },
  {
    number: 11,
    name: "HVAC",
    items: [
      "Indoor unit locations defined",
      "Outdoor unit locations defined",
      "Refrigerant routing defined",
      "Condensate drain routing defined",
    ],
  },
  {
    number: 12,
    name: "Ceiling",
    items: [
      "Ceiling type specified",
      "Suspension system defined",
      "Access panels provided",
      "Lighting cutouts coordinated",
    ],
  },
  {
    number: 13,
    name: "Built-in Furniture",
    items: [
      "Bed platform details defined",
      "Wardrobe fixing details defined",
      "Kitchen cabinet details defined",
      "Vanity fixing details defined",
    ],
  },
  {
    number: 14,
    name: "Finishes",
    items: [
      "Floor finish schedule defined",
      "Wall finishes defined",
      "Ceiling finishes defined",
      "Paint specification provided",
    ],
  },
  {
    number: 15,
    name: "Fire & Safety",
    items: [
      "Fire rated walls defined",
      "Fire rated doors defined",
      "Smoke detectors located",
      "Fire alarms provided",
    ],
  },
  {
    number: 16,
    name: "Fabrication Information",
    items: [
      "Steel cutting lengths provided",
      "Plate thickness specified",
      "Bolt sizes and grades defined",
      "Weld types defined",
      "Surface treatment defined",
    ],
  },
  {
    number: 17,
    name: "Module Assembly",
    items: [
      "Module connection details provided",
      "Bolt connections defined",
      "Joint sealants defined",
      "Alignment tolerances defined",
      "Level adjustment methods defined",
    ],
  },
  {
    number: 18,
    name: "Drawing Quality Control",
    items: [
      "Drawing scale correct",
      "Dimensions complete",
      "Sections referenced",
      "Materials tagged",
      "Revisions updated",
      "Bill of materials attached",
      "Assembly notes included",
    ],
  },
];

export const TOTAL_CHECKLIST_ITEMS = QC_CHECKLIST_SECTIONS.reduce(
  (sum, s) => sum + s.items.length,
  0
);

export const STANDARD_DETAILS = [
  "Steel module base frame detail",
  "Module-to-foundation connection detail",
  "Module-to-module structural connection",
  "Vertical stacking connection",
  "Temporary transport bracing detail",
  "Crane lifting lug / lifting plate detail",
  "Floor build-up assembly detail",
  "Bathroom wet floor depression detail",
  "Bathroom waterproofing edge detail",
  "External wall panel fixing detail",
  "External wall corner detail",
  "Wall-to-floor junction detail",
  "Wall-to-roof junction detail",
  "Roof build-up assembly",
  "Roof waterproofing termination",
  "Roof parapet edge detail",
  "Roof gutter and downpipe detail",
  "Window installation detail",
  "Window sill flashing detail",
  "Window head flashing detail",
  "Door frame fixing detail",
  "Door threshold waterproofing",
  "Internal partition stud wall detail",
  "Acoustic wall assembly",
  "Ceiling suspension detail",
  "Ceiling service access panel",
  "HVAC diffuser ceiling integration",
  "Electrical conduit inside modular wall",
  "Plumbing pipe sleeve through steel",
  "Bathroom pipe shaft access panel",
  "Kitchen cabinet fixing to steel frame",
  "Built-in bed platform structural fixing",
  "Balcony or deck connection to module",
  "Exterior railing fixing to steel",
  "Fire rated wall assembly",
  "Fire stopping around service penetrations",
  "Expansion joint between module banks",
  "Module joint waterproof gasket detail",
  "Exterior cladding attachment system",
  "Transport protection edge detail",
];
